[build]
  command = "cd frontend && npm run build"
  publish = "frontend/.next"

[functions]
  directory = "backend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/backend/api/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
